@startuml
backend->frontend: Send bullets by Websocket 
frontend->user: Show bullets
frontend->localStorage: Save bullets by list of JSON
chat->localStorage: Get bullets
localStorage->chat: Return list of JSON
chat->user: show 20 messages

frontend->voting: Get result
voting->backend: Get award data
backend->voting: Return data by Redis
voting->frontend: Return award data
@enduml
