@startuml
left to right direction
skinparam packageStyle rectangle
actor user
rectangle Container {
  user -- (PGadmin)
  (PGadmin) .> (PostgreSQL)
}
(PGadmin) --> (Create table): [1]
(PGadmin) --> (Find & save DDL): [2]
(PGadmin) --> (Drop table): [3]
(PGadmin) --> (Use DDL to create Table): [4]
@enduml
