@startuml
User->Frontend: 登入遊戲
Frontend->Backend: 取得用戶資訊、彈幕樣式
Backend->Frontend: 回傳設定檔
Frontend->User: 初始化遊戲設定
Chatbot->Backend: 管理者設定所有人的樣式(Style)
Frontend->Backend: Reload 重新載入設定檔
Backend->Frontend: 回傳 admin 設定
Frontend->User: 使用 admin 設定的難度
@enduml
