@startuml
User -right-> (Chatbot): 加好友
(Chatbot) -up-> (Flex 函式): 請求產生樣板
(Flex 函式) <-right-> (資料庫): 取得相關資訊
(Flex 函式) -> (Chatbot): 回應樣板

(主機) -down-> (官方網站): 定時抓取相關數據資訊
(主機) -down-> (Youtube 頻道): 定時抓取相關數據資訊
(主機) -up-> (資料庫): 儲存資料
@enduml
