@startuml

User->Chatbot: 發送訊息
Chatbot->User: 已讀，資訊處理中
Chatbot->LINE: LINE Server 收到資訊
LINE->Chatbot: 已收到，轉至 webhook
LINE->Backend: 透過 webhook 打到 Backend API
Backend->LINE: 200 OK
note over LINE, Backend #ADFF2F: 一般回傳成功


LINE->Backend: 透過 webhook 打到 Backend API
Backend->LINE: 400 || 500... LINE Server 找不到

note over LINE, Backend #FA8072: 失敗回傳後，用戶不知道發生什麼事

@enduml
